### ISSUE TITLE
关于reconstruct function的问题

### ISSUE THREAD

**Issue by yxzhao990302** [ubikpkd/d-gan_informer#1]
您好，关于您exp_informer文件中的reconstruct的作用如果我没理解错的话是执行在论文中提到的iteration strategy（选出一个最佳的z）。但是我看您在predict function代码中将调用reconstruct的function注释掉了，想问下最后的结果使用了iteration strategy吗，是否是已经补充好的数据呢。
非常感谢！

**Comment by ubikpkd** [comment]
您好，最后结果使用了iteration strategy

**Comment by yxzhao990302** [comment]
感谢您的回复！
但是我注意到您将reconstruction函数在predict中的使用注释掉了，是不需要使用reconstruction函数吗，那iteration strategy是从哪部分实现呢。或者我需要解开这部分注释吗？
还有个问题是想问下最后补充好的完整的数据应该如何获得，是predict函数生成的preds吗？
非常感谢！

**Comment by ubikpkd** [comment]
注释掉的原因是做消融实验，解开注释即可。preds为补充后的数据

**Comment by yxzhao990302** [comment]
好的，非常感谢！
